# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket                      = "main-dev-tf-state"
    encrypt                     = true
    key                         = "infra/solution/terraform.tfstate"
    kms_key_id                  = "arn:aws:kms:eu-central-1:XXXXXXXXXXXX:key/XXXXX-XXXXX-XXXX-XXXX-XXXXX"
    dynamodb_table              = "terraform-lock-solution"
    profile                     = "default"
    region                      = "eu-central-1"
    skip_credentials_validation = true
    skip_metadata_api_check     = true
    skip_region_validation      = true
    assume_role = {
      role_arn = "arn:aws:iam::XXXXXXXXXXXX:role/OrganizationAccountAccessRole"
    }
  }
}
